apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-manager
  namespace: blockchain-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pool-manager
  template:
    metadata:
      labels:
        app: pool-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        node-role: apps
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: pool-manager
          image: ghcr.io/lucasrueda01/blockchain-pool-manager
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - configMapRef:
                name: blockchain-app-config
            - secretRef:
                name: rabbitmq-credentials
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 600m
              memory: 512Mi

