apiVersion: v1
kind: Service
metadata:
  name: pool-manager
  namespace: blockchain-apps
  labels:
    app: pool-manager
spec:
  type: ClusterIP
  selector:
    app: pool-manager
  ports:
    - name: http
      port: 6000
      targetPort: 6000
    - name: metrics
      port: 8000
      targetPort: 8000