apiVersion: v1
kind: Service
metadata:
  name: pool-manager
  namespace: blockchain-apps
spec:
  type: LoadBalancer
  loadBalancerIP: ${POOL_MANAGER_HOST}
  selector:
    app: pool-manager
  ports:
    - port: 6000
      targetPort: 6000