apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-cpu
  namespace: blockchain
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker-cpu
  template:
    metadata:
      labels:
        app: worker-cpu
    spec:
      nodeSelector:
        node-role: apps
      containers:
        - name: worker-cpu
          image: lucasrueda01/worker-cpu:dev2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: blockchain-config
            - secretRef:
                name: rabbitmq-credentials
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBIT_HOST
              value: rabbitmq-external
          
          