apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-app-config
  namespace: blockchain-apps
data:
  REDIS_HOST: redis.blockchain-infra
  REDIS_TCP_PORT: "6379"

  RABBIT_HOST: rabbitmq.blockchain-infra
  RABBIT_TCP_PORT: "5672"
  RABBIT_VHOST: blockchain

  POOL_MANAGER_HOST: pool-manager
  POOL_MANAGER_PORT: "6000"

  COORDINADOR_HOST: coordinator
  COORDINADOR_PORT: "5000"

  HEARTBEAT_TTL: "180"

  PROCESSING_TIME: "15"
  MAX_TRANSACTIONS_PER_BLOCK: "20"

  BUCKET_NAME: bucket-integrador-dulcet-thinker-485219-q1

  DIFFICULTY_LOW: "3"
  DIFFICULTY_HIGH: "6"
  BASE_STRING_CHAIN: "A3F8"
  MAX_RANDOM: "99999999"

  COOPERATIVE_MINING: "True"

  DEBUG: "True"
  TZ: "America/Argentina/Buenos_Aires"
