apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-config
  namespace: blockchain-demo
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"

  RABBIT_HOST: rabbitmq
  RABBIT_USER: guest
  RABBIT_PASSWORD: guest

  QUEUE_NAME_TX: QueueTransactions
  EXCHANGE_BLOCK: ExchangeBlock

  COORDINADOR_HOST: coordinator
  COORDINADOR_PORT: "5000"

  PREFIX: "000"
  BASE_STRING_CHAIN: "A3F8"

  MAX_RANDOM: "99999999"
  MAX_TRANSACTIONS_PER_BLOCK: "20"
  TIMER: "15"
  BUCKET_NAME: bucket-integrador-dulcet-thinker-485219-q1
