apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - blockchain-apps-config.yaml
  - blockchain-infra-config.yaml

  - coordinator/coordinator-deployment.yaml
  - coordinator/coordinator-service.yaml

  - cpu-scaler/cpu-scaler-deployment.yaml
  - cpu-scaler/cpu-scaler-service-account.yaml

  - pool-manager/pool-manager-deployment.yaml
  - pool-manager/pool-manager-service.yaml

  - rabbitmq/rabbitmq-secret-apps.yaml
  - rabbitmq/rabbitmq-secret-infra.yaml
  - rabbitmq/rabbitmq-service.yaml
  - rabbitmq/rabbitmq-service-external.yaml
  - rabbitmq/rabbitmq-statefulset.yaml

  - redis/redis-service.yaml
  - redis/redis-statefulset.yaml

images:
  - name: ghcr.io/lucasrueda01/blockchain-coordinator
  - name: ghcr.io/lucasrueda01/blockchain-cpu-scaler
  - name: ghcr.io/lucasrueda01/blockchain-pool-manager