apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # RabbitMQ
  - rabbitmq/rabbitmq-secret.yaml
  - rabbitmq/rabbitmq-cluster.yaml
  - rabbitmq/rabbitmq-service-monitor.yaml

  # Redis
  - redis/redis-service.yaml
  - redis/redis-statefulset.yaml
