apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - blockchain-infra-config.yaml

  # RabbitMQ
  - rabbitmq/rabbitmq-secret-infra.yaml
  - rabbitmq/rabbitmq-service.yaml
  - rabbitmq/rabbitmq-statefulset.yaml

  # Redis
  - redis/redis-service.yaml
  - redis/redis-statefulset.yaml
