apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: blockchain-apps
spec:
  type: LoadBalancer
  loadbalancerIP: ${COORDINATOR_HOST}
  selector:
    app: coordinator
  ports:
    - port: 5000
      targetPort: 5000