apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-scaler
  namespace: blockchain-infra

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-scaler
  template:
    metadata:
      labels:
        app: cpu-scaler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        node-role: infra
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: cpu-scaler
      restartPolicy: Always

      volumes:
        - name: worker-cpu-script
          configMap:
            name: worker-cpu-startup

      containers:
        - name: cpu-scaler
          image: ghcr.io/lucasrueda01/blockchain-cpu-scaler
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBIT_EXTERNAL_HOST
              value: ${RABBIT_EXTERNAL_HOST}
            - name: COORDINADOR_EXTERNAL_HOST
              value: ${COORDINADOR_EXTERNAL_HOST}
            - name: POOL_MANAGER_EXTERNAL_HOST
              value: ${POOL_MANAGER_EXTERNAL_HOST}

          envFrom:
            - configMapRef:
                name: blockchain-infra-config

          volumeMounts:
            - name: worker-cpu-script
              mountPath: /scripts/worker_cpu_startup.sh
              subPath: worker_cpu_startup.sh

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
