apiVersion: v1
kind: Service
metadata:
  name: cpu-scaler
  namespace: blockchain-infra
  labels:
    app: cpu-scaler
spec:
  selector:
    app: cpu-scaler
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
