apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-scaler
  namespace: blockchain
  annotations:
    iam.gke.io/gcp-service-account: cpu-scaler@dulcet-thinker-485219-q1.iam.gserviceaccount.com
