apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-scaler
  namespace: blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-scaler
  template:
    metadata:
      labels:
        app: cpu-scaler
    spec:
      nodeSelector:
        node-role: apps
      serviceAccountName: cpu-scaler
      restartPolicy: Always

      containers:
        - name: cpu-scaler
          image: lucasrueda01/cpu-scaler:dev3
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - configMapRef:
                name: blockchain-config

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
