apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-manager
  namespace: blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pool-manager
  template:
    metadata:
      labels:
        app: pool-manager
    spec:
      nodeSelector:
        node-role: apps
      containers:
        - name: coordinator
          image: lucasrueda01/pool_manager:dev4 
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - configMapRef:
                name: blockchain-config
            - secretRef:
                name: rabbitmq-credentials
