apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-manager
  namespace: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool-manager
  template:
    metadata:
      labels:
        app: pool-manager
    spec:
      containers:
        - name: coordinator
          image: lucasrueda01/pool-manager:dev2 
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - configMapRef:
                name: blockchain-config
