apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-external
  namespace: blockchain-infra
spec:
  type: LoadBalancer
  loadBalancerIP: ${RABBIT_IP}
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
