apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blockchain-ingress
  namespace: blockchain-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ${INGRESS_IP}.nip.io
      http:
        paths:
          - path: /coordinator(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: coordinator
                port:
                  number: 5000

          - path: /pool(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pool-manager
                port:
                  number: 6000
