controller:
  extraArgs:
    tcp-services-configmap: "ingress-nginx/tcp-services"

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: ${INGRESS_IP}

    ports:
      http: 80
      https: 443
      amqp: 5672

    targetPorts:
      http: http
      https: https
      amqp: 5672
