apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coordinator-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: coordinator
  namespaceSelector:
    matchNames:
      - blockchain-apps
  endpoints:
    - port: http
      path: /coordinator/metrics
      interval: 10s
