apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pool-manager-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: pool-manager
  namespaceSelector:
    matchNames:
      - blockchain-apps
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
