apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-infra-config
  namespace: blockchain-infra
data:
  REDIS_HOST: redis
  REDIS_TCP_PORT: "6379"

  CPUS_PER_GPU: "3"
  EXPECTED_GPUS: "1"
  SCALE_COOLDOWN: "90"
  SCALE_INTERVAL: "30"

  CPU_CAPACITY: "10"
  GPU_CAPACITY: "100"

  AUTOSCALER : "False"

  DEBUG: "True"
  TZ: "America/Argentina/Buenos_Aires"
