name: pipeline-1-infra

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.6.6
  TF_WORKING_DIR: blockchain/infraestructura/terraform/terraform-cluster
  REGION: us-central1
  ZONE: us-central1-a

jobs:
  terraform:
    name: Deploy Base Infrastructure (Cluster)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # üîê Autenticaci√≥n con GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # üèóÔ∏è Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init (remote backend)
        run: |
          cd $TF_WORKING_DIR
          terraform init -input=false

      - name: Terraform Validate
        run: |
          cd $TF_WORKING_DIR
          terraform validate

      - name: Terraform Plan
        run: |
          cd $TF_WORKING_DIR
          terraform plan \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=$REGION" \
            -out=tfplan

      - name: Terraform Apply
        run: |
          cd $TF_WORKING_DIR
          terraform apply -auto-approve tfplan
